[gcp_service_account]
type = "service_account"
project_id = "proyecto-css-panama"
private_key_id = "6d5020c3a52de2af1db561a994bd1a88b6a2e3a1"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD+xNEkE9oFRd+e
bbieRfcBRrT9OHhzme2Q2hDKqDQPRCWCcjhkzKvefiDoaO5KnjD2VlYbuKeiGXQL
/tJAUIhcYTinzeuQF5nsYqC6iyX6xcpHUTjSwmaWapPKhuprlkUao9mzUo6PYZkF
VZjhTMZjAg7k2zuRXcLvhRuG+kqyxV5d/R7bXRy+2Fwj+LR5uilXzgzkws394It9
08jrzGXeMazNfpju+IdDBy5B2BOQ+TQYR5XuMLpRckArMUVgLu1fnkxEZ/+pVz2u
e3ZJePcRy9hWtxCa126ctu4onuIwguZyo9lih2use/9KyGhXBrfI8+OyeKihhsjR
ptahjN+/AgMBAAECggEAdG6AYiuMZQKE6wOb7wFsnDGzP1KSgcpkLuHp8KQkfqGX
PuFycmazWVBtO6nQ1VssZzgXzD18pvFY/q5raicj2ow390B9mnGez9BXQkmbhtrj
0eoFvRRJDA8TEejMs3SOilk9gd2F93MUGsL+xmBu/gqPwfmLZKjkENDVPr+eacou
I556j/4Eeh1V6pFYNsq65yb2E4sILVWHtycMMFsoOyQemNdUjUEYwVjmH8cZk5Xe
unmwas3Xp+KVHcq0C+VZCvAF7EF7XZ3xwrQS9VJKCl/pW+rvP6ZvF8Ozx247roV9
8jxNxxTgM95Ty8dbzq5mMz+AiL4DgnC3IEzeKabYWQKBgQD/fXQg/pZK4DmHKS2+
d6PhI+eDjGAgaSJPcqpRNNQFXLJdu+heKFss+YLQM+JcXsyvB2JtnARE5xLuTN50
2qe+2SdmIdQ/BKyU+PDszK/x3Z6HnzK0cJFQ8zebTlXEqEct9IbBh+PAw7yXeJKy
Q1LeYwaSd2NZFxIqIPwvfnqBwwKBgQD/Rv6rU2HqPKALn5Lo4NsLGWEjDjPbvejM
tZJHug2GyWCGFFTFZA8OqCw5Qt2b9V1ZCTLyhSXDHw0yh+dBu+KuWPvWEoNpz3gF
iSgO2yUuxa2R2USNlKFtxjE/fe6XCucfxZwQKH/lDwA2yM50dYQYs9Iwp6wDsmL3
Alg4BIpuVQKBgEtPOYn4QWj0y0BSHQ/FyGK26KlYGYW0N87fZ+DkB5NFDbafixEm
KCoLqkmg4ZqEvyTgslzI3mFJE8V2lyQux79z1y89zYh94jlPYAUNGNfckbw8av/R
JqSL7No0rwd26vRa3dXyLmpFyDOF8Qfm3Gh9HBTUaE58hHgynOOLDqVtAoGBAKyC
TZd5wbGJRp6UN7MoQN4/SGVoM6NLswajrTbLhFiRvajeFGtQMty0yS3pAdli9rI0
hTlewSYa1dBQBvdlAMrRV15TJHtcuL8E8Q0ZCweQjrsBGFKVHoIQbTd64sEvnQDb
iZthwwwIFxzulpYc1CfdXS2EIbpd0oMaEoPIjcQBAoGBAN3JGOwFzgeOiHzNatWM
wYwSLK20dWdu7EpWqVicVzqZAx5ZuL5cGbwkvgpVNDFNA6wHl1lDch1i9MYR4Nvq
LNZ3FnkkiNOn3ZL2vzBH6AalwfOBk6222FWp0pnpXDf+y4x1ODKVYINB/oE67Gvy
k/QWob3746dUI0kQBrJ7+YBT
-----END PRIVATE KEY-----"""
client_email = "investigacion-css@proyecto-css-panama.iam.gserviceaccount.com"
client_id = "102166342992162842227"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/investigacion-css%40proyecto-css-panama.iam.gserviceaccount.com"
